apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: rook-ceph
spec:
  containers:
    - command:
        - sh
        - -c
        - |
          sleep infinity
      image: ghcr.io/ushitora-anqou/ceph:dev
      imagePullPolicy: IfNotPresent
      name: foobar
